### ISSUE TITLE
Maker the tags respect ignore titlecase, but respect later caps

### ISSUE THREAD

**Issue by philhawksworth** [netlify/templates#10]
**- Do you want to request a *feature* or report a *bug*?**

Bug

**- What is the current behavior?**

The [tags listing](https://templates.netlify.com/tags/netlifyCMS) reveals that tags are case senstive and that we have different capitalizations of the same tag present.

**- What is the expected behavior?**

Tags should be ignore sentence-case or title-case and normalize the tag internally as lowercase for consistency, but should display with Titlecase.

We should also honor the capitalization of later letters in the tag incase they carry specific importnace such as in `NetlifyCMS`. 

This should be stored internally as `netlifyCMS` (regardless is it was entered calitalized or not) but rendered as `NetlifyCMS`

**Comment by karlkeefer** [comment]
:+1: came here because I wanted to filter the list by netlifyCMS
