### ISSUE TITLE
Deploy preview fails when adding a template

### ISSUE THREAD

**Issue by jaepass** [netlify/templates#103]
**- Do you want to request a *feature* or report a *bug*?**
Feature

**- What is the current behavior?**
Build fails for deploy preview and produces this error in the log `Error checking out repo`

**- What is the expected behavior?**
Build to pass and produces a deploy preview

**Comment by philhawksworth** [comment]
@jaepass Is the repo for your template publicly available?
Could you link it here so I could see explore with the issue might be?

Also, do you have a PR for including this in the site which I could review against?

**Comment by jaepass** [comment]
Hi Phil, this was fixed couple weeks ago apologies, should have referenced the issue. I have now closed it! Thank you!
https://github.com/netlify/templates/pull/102
