### ISSUE TITLE
[🚨 Announcement!] templates.netlify.app soon to be moved

### ISSUE THREAD

**Issue by tzmanics** [netlify/templates#277]
Thank you for your interest in our template site. We have recently decided we are going to move Netlify templates to a dedicated integration page on [netlify.com](http://netlify.com/)! We will be redirecting users from netlify.templates to this page towards the end of September 2022 (specific details to come).

We still love the idea of working with partners throughout our ecosystem. If this sounds good to you, we have this document that will walk you through this partnership process: [Netlify Ecosystem Partner Template Process](https://asset.cloudinary.com/dzkoxrsdj/0058b841daff62a3bdb1886222692a70).

Please feel free to reach out to us at [templates@netlify.com](mailto:templates@netlify.com) if you have any questions or concerns.

Thank you!

**Comment by MarcL** [comment]
This has now happened with the merge of #301. Closing this issue. 👍🏻 🎄
