### ISSUE TITLE
"Deploy To Netlify" deploys from Kaldi repo that is no longer maintained

### ISSUE THREAD

**Issue by gp-dublincentral** [netlify/templates#36]
**What happens**
On
https://templates.netlify.com/template/hugo-starter-blog-theme-kaldi/ (and from https://templates.netlify.com/) if you click on "Deploy To Netlify" it deploys from the repo https://github.com/netlify-templates/kaldi-hugo-cms-template. Per the readme in that repo it's no longer maintained.

**What should happen**
The readme identifies https://github.com/netlify-templates/one-click-hugo-cms as the maintained repository, clicking on "Deploy To Netlify" should deploy from that repo

**Comment by maxcell** [comment]
Thank you for this report, this should be resolved now!
